services:
    apwa.pmwelcome.admin.controller:
        class: apwa\pmwelcome\controller\admin_controller
        arguments:
            - '@config'
            - '@config_text'
            - '@dbal.conn'
            - '@language'
            - '@log'
            - '@request'
            - '@template'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'
    apwa.pmwelcome.listener:
        class: apwa\pmwelcome\event\listener
        arguments:
            - '@config'
            - '@config_text'
            - '@dbal.conn'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }
